---
title: "Organise your data and figures"
author: "Rich Cottrell"
date: '2023-05-02'
output: pdf_document
---

Load the libraries needed.

```{r setup, include=FALSE}

library(tidyverse)
library(janitor)

```

Tidy the data as before.

```{r, message=FALSE}


(fisheries_final <- 
  readRDS("data/input/fisheries_prod_raw.rds") |> 
  clean_names() |> 
  pivot_longer(names_to = "year", values_to = "value", 
               cols = -c(country_country, species_asfis_species, fishing_area_fao_major_fishing_area, unit_unit)) |> 
                 filter(!country_country %in% c("Totals - Tonnes - live weight",   "Totals - Number" , "FAO. 2019. Fishery and Aquaculture Statistics. Global capture production 1950-2017 (FishstatJ). In: FAO Fisheries and Aquaculture Department [online]. Rome. Updated 2019. www.fao.org/fishery/statistics/software/fishstatj/en")) |> 
                 mutate(year = gsub("x", "", year) |>    
            as.numeric(),                   
          flag = case_when(value == "..." ~ "No data",                      
                           value == " " ~ "Data not separately available",
                           value == "-" ~ "Nil or zero",                 
                           value == "0 0" ~ "0<x<0.5",
                           grepl(" F", value) ~ "estimate",
                           TRUE ~ "Reported"),                          
          value = case_when(value %in% c("...", " ", "-") ~ "0",        
                            value == "0 0" ~ "0.25",                    
                            grepl(" F", value) ~ gsub(" F", "", value), 
                            TRUE ~ value) |>                         
            as.numeric()) |> 
  rename(country = country_country,
         species = species_asfis_species,
         area = fishing_area_fao_major_fishing_area) |> 
  select(-unit_unit) |> 
  group_by(country, year) |> 
  summarise(sum_value = sum(value, na.rm = TRUE)) |> 
  ungroup() |> 
  group_by(country) |> 
  nest() |> 
  mutate(rel_value = purrr::map(data, ~(.$sum_value/.$sum_value[1]))) |> 
  unnest(cols = c(data, rel_value)) |> 
  ungroup() |> 
  left_join(GDP, by = c("country", "year")) 
                 )

```

From the tidied data - create intermediate products for each country and save them.

```{r}


fisheries_list <- 
  fisheries_final |> 
  mutate(country = gsub(pattern = "/", replacement = "", country)) |> #remove forward slashes from country names because R thinks these are part of the file path
  mutate(country = case_when(grepl("Cura", country) ~ "Curacao",
                             grepl("Ivoire", country) ~ "Cote d'Ivoire",
                             grepl("union", country)~ "Reunion",
                             grepl("Saint Barth", country) ~ "St Barth",
                             TRUE ~ country)) |> #fixes countries where special symbols have corrupted
  group_by(country) |> 
  group_split()


map(.x = fisheries_list, .f = \(this_country_df){
  
  this_country_name <- this_country_df |> pull(country) |> unique()
  
  message("Processing landings data for ", this_country_name)
  
  saveRDS(object = this_country_df, file = sprintf("data/int_/%s_fisheries_summarised.rds", this_country_name))

})



```

Now select a specific country, add a new variable, and save it as an output.

```{r}

(aus_landings <- 
  readRDS("data/int/Australia_fisheries_summarised.rds") |> 
  select(-gdp_millions, -rel_value) |> 
  mutate(cum_value = cumsum(sum_value))
)

write_csv(x = aus_landings, file = "data/output/aus_summarised.csv")


```

Create a figure from the finalised data and save it in the figures folder.

```{r}

read_csv("data/output/aus_summarised.csv") |> 
  ggplot() +
  geom_line(aes(x = year, y = sum_value), col = "dodgerblue4")+
  #geom_line(aes(x = year, y = cum_value), col = "firebrick4")+
  labs(y = "Landings (tonnes)")+
  theme_bw()+
  theme(text = element_text(size=8))+
  scale_y_continuous(labels = scales::label_comma())

ggsave(plot = last_plot(), filename = "figures/landings_for_australia.jpg", device = "jpg", dpi = 600, width = 9, height = 7, units = "cm")
  
  

```
